// renderers/react/src/v0_9/catalog/basic/components/Row.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {createComponentImplementation} from '../../../adapter';
import {RowApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {ChildList} from './ChildList';
import {mapJustify, mapAlign, getWeightStyle, useBasicCatalogStyles} from '../utils';

export const Row = createComponentImplementation(RowApi, ({props, buildChild, context}) => {
  useBasicCatalogStyles();
  return (
    <div
      style={{
        ...getWeightStyle(props.weight),
        display: 'flex',
        flexDirection: 'row',
        justifyContent: mapJustify(props.justify),
        alignItems: mapAlign(props.align),
        gap: 'var(--a2ui-row-gap, var(--a2ui-spacing-m))',
      }}
    >
      <ChildList childList={props.children} buildChild={buildChild} context={context} />
    </div>
  );
});

// renderers/lit/src/v0_9/catalogs/basic/components/Row.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing, css, PropertyValues } from "lit";
import { customElement } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { RowApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { BasicCatalogA2uiLitElement } from "../basic-catalog-a2ui-lit-element.js";
import { A2uiController } from "@a2ui/lit/v0_9";

const JUSTIFY_MAP: Record<string, string> = {
  start: "flex-start",
  center: "center",
  end: "flex-end",
  spaceBetween: "space-between",
  spaceAround: "space-around",
  spaceEvenly: "space-evenly",
  stretch: "stretch",
};

const ALIGN_MAP: Record<string, string> = {
  start: "flex-start",
  center: "center",
  end: "flex-end",
  stretch: "stretch",
};

@customElement("a2ui-basic-row")
export class A2uiBasicRowElement extends BasicCatalogA2uiLitElement<typeof RowApi> {
  /**
   * The styles of the row can be customized by redefining the following
   * CSS variables:
   *
   * - `--a2ui-row-gap`: The gap between items in the row. Defaults to `--a2ui-spacing-m`.
   */
  static styles = css`
    :host {
      display: flex;
      flex-direction: row;
      gap: var(--a2ui-row-gap, var(--a2ui-spacing-m));
    }
  `;

  protected createController() {
    return new A2uiController(this, RowApi);
  }

  updated(changedProperties: PropertyValues) {
    super.updated(changedProperties);
    const props = this.controller.props;
    if (props) {
      this.style.justifyContent = JUSTIFY_MAP[props.justify ?? ""] ?? "flex-start";
      this.style.alignItems = ALIGN_MAP[props.align ?? ""] ?? "stretch";
    }
  }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    const children = Array.isArray(props.children) ? props.children : [];

    return html`
      ${map(children, (child: any) => html`${this.renderNode(child)}`)}
    `;
  }
}

export const A2uiRow = {
  ...RowApi,
  tagName: "a2ui-basic-row",
};
