// tree/main/samples/agent/adk/gemini_enterprise/agent_engine/renderers/lit/src/v0_9/catalogs/basic/components/Text.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing, css } from "lit";
import { customElement } from "lit/decorators.js";
import { consume } from "@lit/context";
import { TextApi } from "@a2ui/web_core/v0_9/basic_catalog";
import { BasicCatalogA2uiLitElement } from "../basic-catalog-a2ui-lit-element.js";
import { A2uiController, Context } from "@a2ui/lit/v0_9";
import * as Types from "@a2ui/web_core/types/types";

import { markdown } from "../../../directives/directives.js";

@customElement("a2ui-basic-text")
export class A2uiBasicTextElement extends BasicCatalogA2uiLitElement<typeof TextApi> {
  /**
   * The styles of the text component can be customized by redefining the following
   * CSS variables:
   *
   * - `--a2ui-text-color-text`: The color of the text. Defaults to `--a2ui-color-on-background`.
   * - `--a2ui-text-caption-color`: The color for caption text. Defaults to `light-dark(#666, #aaa)`.
   *
   * It also supports `--_a2ui-text-color` override from parent components (like Button).
   */
  static styles = css`
    :host {
      display: inline-block;
      color: var(--_a2ui-text-color, var(--a2ui-text-color-text, var(--a2ui-color-on-background)));
    }
    p, h1, h2, h3, h4, h5, h6, ol, ul, li, blockquote, pre {
      margin: var(--_a2ui-text-margin, 0);
    }
    h1, h2, h3, h4, h5 {
      font-family: var(--a2ui-font-family-title, inherit);
      line-height: var(--a2ui-line-height-headings, 1.2);
    }
    h1 { font-size: var(--a2ui-font-size-2xl); }
    h2 { font-size: var(--a2ui-font-size-xl); }
    h3 { font-size: var(--a2ui-font-size-l); }
    p, h4 { font-size: var(--a2ui-font-size-m); }
    h5 { font-size: var(--a2ui-font-size-s); }
    p, ol, ul, li, blockquote, .a2ui-caption {
      line-height: var(--a2ui-line-height-body, 1.5);
    }
    .a2ui-caption, .a2ui-caption > *, .a2ui-caption ::slotted(*) {
      font-size: var(--a2ui-font-size-xs);
      color: var(--a2ui-text-caption-color, light-dark(#666, #aaa));
    }
    a {
      color: var(--a2ui-text-a-color, inherit);
      font-weight: var(--a2ui-text-a-font-weight, inherit);
    }
  `;

  // Retrieve a MarkdownRenderer provided by the application.
  @consume({ context: Context.markdown, subscribe: true })
  accessor markdownRenderer: Types.MarkdownRenderer | undefined;

  protected createController() {
    return new A2uiController(this, TextApi);
  }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    // Use props.variant to convert props.text to markdown
    let markdownText = typeof props.text === "string" ? props.text : String(props.text ?? "");
    switch (props.variant) {
      case "h1":
        markdownText = `# ${markdownText}`;
        break;
      case "h2":
        markdownText = `## ${markdownText}`;
        break;
      case "h3":
        markdownText = `### ${markdownText}`;
        break;
      case "h4":
        markdownText = `#### ${markdownText}`;
        break;
      case "h5":
        markdownText = `##### ${markdownText}`;
        break;
      default:
        break; // body and caption.
    }

    const renderedMarkdown = markdown(markdownText, this.markdownRenderer);
    // There's not a good way to handle the caption variant in markdown, so we
    // tag it with a class so it can be tweaked via CSS.
    if (props.variant === "caption") {
      return html`<span class="a2ui-caption">${renderedMarkdown}</span>`;
    }
    return html`${renderedMarkdown}`;
  }
}

export const A2uiText = {
  ...TextApi,
  tagName: "a2ui-basic-text",
};

// renderers/angular/src/v0_9/catalog/basic/text.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  Component,
  computed,
  ChangeDetectionStrategy,
  inject,
  signal,
  effect,
} from '@angular/core';
import { MarkdownRenderer } from '../../core/markdown';
import { BasicCatalogComponent } from './basic-catalog-component';
import { TextApi } from '@a2ui/web_core/v0_9/basic_catalog';

/**
 * Angular implementation of the A2UI Text component (v0.9).
 *
 * Renders text with support for simple Markdown.
 *
 * Supported CSS variables:
 * - `--a2ui-text-color-text`: Controls the text color.
 * - `--a2ui-text-margin`: Controls the margin of text elements.
 * - `--a2ui-font-family-title`: Controls the font family for titles.
 * - `--a2ui-line-height-headings`: Controls the line height for headings.
 * - `--a2ui-line-height-body`: Controls the line height for body text.
 * - `--a2ui-text-caption-color`: Controls the color for caption text.
 * - `--a2ui-text-a-color`: Controls the color for links.
 * - `--a2ui-text-a-font-weight`: Controls the font weight for links.
 * - Font sizes: `--a2ui-font-size-2xl`, `--a2ui-font-size-xl`, `--a2ui-font-size-l`, `--a2ui-font-size-m`, `--a2ui-font-size-s`, `--a2ui-font-size-xs`.
 */
@Component({
  selector: 'a2ui-v09-text',
  standalone: true,
  template: ` <span [class]="'a2ui-text ' + variant()" [innerHTML]="resolvedText()"> </span> `,
  // We use :host ::ng-deep because the template content is injected via innerHTML (Markdown).
  // Angular's default view encapsulation cannot target elements injected via innerHTML because they lack the scoping attributes generated at compile time.
  // ::ng-deep allows styles to reach into the injected HTML, while :host keeps them scoped to this component.
  styles: [
    `
      :host ::ng-deep .a2ui-text p,
      :host ::ng-deep .a2ui-text h1,
      :host ::ng-deep .a2ui-text h2,
      :host ::ng-deep .a2ui-text h3,
      :host ::ng-deep .a2ui-text h4,
      :host ::ng-deep .a2ui-text h5,
      :host ::ng-deep .a2ui-text h6,
      :host ::ng-deep .a2ui-text ol,
      :host ::ng-deep .a2ui-text ul,
      :host ::ng-deep .a2ui-text li,
      :host ::ng-deep .a2ui-text blockquote,
      :host ::ng-deep .a2ui-text pre {
        margin: var(--_a2ui-text-margin, 0);
      }
      :host ::ng-deep .a2ui-text {
        color: var(
          --_a2ui-text-color,
          var(--a2ui-text-color-text, var(--a2ui-color-on-background))
        );
      }
      :host ::ng-deep .a2ui-text h1,
      :host ::ng-deep .a2ui-text h2,
      :host ::ng-deep .a2ui-text h3,
      :host ::ng-deep .a2ui-text h4,
      :host ::ng-deep .a2ui-text h5,
      :host ::ng-deep .a2ui-text h6 {
        font-family: var(--a2ui-font-family-title, inherit);
        line-height: var(--a2ui-line-height-headings, 1.2);
      }
      :host ::ng-deep .a2ui-text h1 {
        font-size: var(--a2ui-font-size-2xl);
      }
      :host ::ng-deep .a2ui-text h2 {
        font-size: var(--a2ui-font-size-xl);
      }
      :host ::ng-deep .a2ui-text h3 {
        font-size: var(--a2ui-font-size-l);
      }
      :host ::ng-deep .a2ui-text p,
      :host ::ng-deep .a2ui-text h4 {
        font-size: var(--a2ui-font-size-m);
      }
      :host ::ng-deep .a2ui-text h5 {
        font-size: var(--a2ui-font-size-s);
      }
      :host ::ng-deep .a2ui-text p {
        line-height: var(--a2ui-line-height-body, 1.5);
      }
      :host ::ng-deep .a2ui-text.caption {
        font-size: var(--a2ui-font-size-xs);
        color: var(--a2ui-text-caption-color, light-dark(#666, #aaa));
      }
      :host ::ng-deep .a2ui-text a {
        color: var(--a2ui-text-a-color, inherit);
        font-weight: var(--a2ui-text-a-font-weight, inherit);
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TextComponent extends BasicCatalogComponent<typeof TextApi> {
  private markdownRenderer = inject(MarkdownRenderer);

  readonly variant = computed(() => this.props()['variant']?.value() || 'body');
  readonly text = computed(() => this.props()['text']?.value() || '');

  resolvedText = signal<string>('');
  private renderRequestId = 0;

  constructor() {
    super();
    effect(() => {
      const text = this.text();
      const variant = this.variant();
      let value = text;

      switch (variant) {
        case 'h1':
          value = `# ${text}`;
          break;
        case 'h2':
          value = `## ${text}`;
          break;
        case 'h3':
          value = `### ${text}`;
          break;
        case 'h4':
          value = `#### ${text}`;
          break;
        case 'h5':
          value = `##### ${text}`;
          break;
        case 'caption':
          value = `*${text}*`;
          break;
      }

      const requestId = ++this.renderRequestId;
      this.markdownRenderer.render(value).then((rendered) => {
        if (requestId === this.renderRequestId) {
          this.resolvedText.set(rendered);
        }
      });
    });
  }
}
